apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-service
  namespace: mlops
  labels:
    app: cats-dogs
spec:
  type: LoadBalancer
  selector:
    app: cats-dogs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  sessionAffinity: None
